repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        name: prettier + plugin-xml
        additional_dependencies:
          - "prettier@2.1.2"
          - "@prettier/plugin-xml@0.12.0"
        args:
          - --config=odoo/.prettierrc.yml
          - --plugin=@prettier/plugin-xml
          - --ignore-path=odoo/.prettierignore

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.8.1
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
          - --config=odoo/.eslintrc.yml
          - --ignore-path=odoo/.eslintignore

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args:
          - --config=odoo/.flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.1
    hooks:
      - id: isort
        name: isort
        args:
          - --settings=odoo/

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.3
    hooks:
      - id: pylint
        name: pylint
        args:
          - --rcfile=odoo/.pylintrc
          - --exit-zero
        verbose: true
        additional_dependencies: &pylint_deps
          - pylint-odoo==3.5.0
