# This file is used to allow developer access to the database and
# the usage of GUI database tools. Do not use in production systems

version: '3'

services:
  db:
    networks:
      default:
      public:
    ports:
      - "127.0.0.1:${DATABASE_PORT:-6543}:5432"
