version: '3'

services:
  # Odoo
  odoo:
    depends_on:
      - mailhog
    environment:
      ODOO_SMTP_SERVER: mailhog
      ODOO_SMTP_PORT: 1025

  mailhog:
    image: mailhog/mailhog:latest
    networks:
      default:
      public:
    ports:
      - ${MAILHOG_PORT:-127.0.0.1:8025}:8025

networks:
  default:
    internal: True
  public:
